
//
// Created by Brandon Martin on 8/12/18.
//

#ifndef UNO_ONLINE_MULTIPLAYER_CONSTANTS_H
#define UNO_ONLINE_MULTIPLAYER_CONSTANTS_H

enum class CardColors {
    RED, GREEN, BLUE, YELLOW, WILD
};

enum class CardValues {
    ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, ZERO, SKIP, REVERSE, PLUS2, PLUS4, WILD
};

#endif //UNO_ONLINE_MULTIPLAYER_CONSTANTS_H
